dist: trusty
sudo: false

language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"
branches:
  only:
    - master

script:
  - echo asdsadsdasd
  - node test.js
  - export CHROME_BIN=chromium-browser
  - yarn test
  - xvfb-run -a yarn test
